// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace SGSandbox.Models.Customer
{

    public class Assortment
    {

        [JsonProperty("assortmentId")]
        public string AssortmentId { get; set; }

        [JsonProperty("validFrom")]
        public string ValidFrom { get; set; }

        [JsonProperty("validTo")]
        public string ValidTo { get; set; }
    }

    public class LicenceCode
    {

        [JsonProperty("LicenseCode")]
        public string LicenseCode { get; set; }
    }

    public class Customer
    {

        [JsonProperty("AccountNum")]
        public string AccountNum { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Address")]
        public string Address { get; set; }

        [JsonProperty("Phone")]
        public string Phone { get; set; }

        [JsonProperty("TeleFax")]
        public string TeleFax { get; set; }

        [JsonProperty("InvoiceAccount")]
        public string InvoiceAccount { get; set; }

        [JsonProperty("CustGroup")]
        public string CustGroup { get; set; }

        [JsonProperty("LineDisc")]
        public string LineDisc { get; set; }

        [JsonProperty("PaymTermId")]
        public string PaymTermId { get; set; }

        [JsonProperty("Currency")]
        public string Currency { get; set; }

        [JsonProperty("SalesGroup")]
        public string SalesGroup { get; set; }

        [JsonProperty("Blocked")]
        public string Blocked { get; set; }

        [JsonProperty("OneTimeCustomer")]
        public string OneTimeCustomer { get; set; }

        [JsonProperty("CreditMax")]
        public string CreditMax { get; set; }

        [JsonProperty("MandatoryCreditLimit")]
        public string MandatoryCreditLimit { get; set; }

        [JsonProperty("VendAccount")]
        public string VendAccount { get; set; }

        [JsonProperty("Telex")]
        public string Telex { get; set; }

        [JsonProperty("PriceGroup")]
        public string PriceGroup { get; set; }

        [JsonProperty("MultiLineDisc")]
        public string MultiLineDisc { get; set; }

        [JsonProperty("EndDisc")]
        public string EndDisc { get; set; }

        [JsonProperty("VATNum")]
        public string VATNum { get; set; }

        [JsonProperty("CountryRegionId")]
        public string CountryRegionId { get; set; }

        [JsonProperty("DlvTerm")]
        public string DlvTerm { get; set; }

        [JsonProperty("DlvMode")]
        public string DlvMode { get; set; }

        [JsonProperty("MarkupGroup")]
        public string MarkupGroup { get; set; }

        [JsonProperty("ZipCode")]
        public string ZipCode { get; set; }

        [JsonProperty("URL")]
        public string URL { get; set; }

        [JsonProperty("Email")]
        public string Email { get; set; }

        [JsonProperty("CellularPhone")]
        public string CellularPhone { get; set; }

        [JsonProperty("PhoneLocal")]
        public string PhoneLocal { get; set; }

        [JsonProperty("TaxGroup")]
        public string TaxGroup { get; set; }

        [JsonProperty("PaymMode")]
        public string PaymMode { get; set; }

        [JsonProperty("BankAccount")]
        public string BankAccount { get; set; }

        [JsonProperty("ContactPersonId")]
        public string ContactPersonId { get; set; }

        [JsonProperty("InvoiceAddress")]
        public string InvoiceAddress { get; set; }

        [JsonProperty("OurAccountNum")]
        public string OurAccountNum { get; set; }

        [JsonProperty("SalesPoolId")]
        public string SalesPoolId { get; set; }

        [JsonProperty("InclTax")]
        public string InclTax { get; set; }

        [JsonProperty("LanguageId")]
        public string LanguageId { get; set; }

        [JsonProperty("City")]
        public string City { get; set; }

        [JsonProperty("Street")]
        public string Street { get; set; }

        [JsonProperty("SMS")]
        public string SMS { get; set; }

        [JsonProperty("SalesCalendarId")]
        public string SalesCalendarId { get; set; }

        [JsonProperty("CustClassificationId")]
        public string CustClassificationId { get; set; }

        [JsonProperty("InventSiteId")]
        public string InventSiteId { get; set; }

        [JsonProperty("PartyId")]
        public string PartyId { get; set; }

        [JsonProperty("Memo")]
        public string Memo { get; set; }

        [JsonProperty("SalesDistrictId")]
        public string SalesDistrictId { get; set; }

        [JsonProperty("SegmentId")]
        public string SegmentId { get; set; }

        [JsonProperty("SubsegmentId")]
        public string SubsegmentId { get; set; }

        [JsonProperty("CompanyChainId")]
        public string CompanyChainId { get; set; }

        [JsonProperty("MainContactId")]
        public string MainContactId { get; set; }

        [JsonProperty("PaymIdType")]
        public string PaymIdType { get; set; }

        [JsonProperty("EO_BreakAddition")]
        public string EOBreakAddition { get; set; }

        [JsonProperty("EO_PriorityCode")]
        public string EOPriorityCode { get; set; }

        [JsonProperty("EO_PriorityDlvTime")]
        public string EOPriorityDlvTime { get; set; }

        [JsonProperty("EO_EANLocationCust")]
        public string EOEANLocationCust { get; set; }

        [JsonProperty("EO_CustNoInChain")]
        public string EOCustNoInChain { get; set; }

        [JsonProperty("EO_InvoiceType")]
        public string EOInvoiceType { get; set; }

        [JsonProperty("EO_CustPurchaseOrder")]
        public string EOCustPurchaseOrder { get; set; }

        [JsonProperty("EO_CustRef")]
        public string EOCustRef { get; set; }

        [JsonProperty("EO_NoBreakage")]
        public string EONoBreakage { get; set; }

        [JsonProperty("EO_EANLocationUNB")]
        public string EOEANLocationUNB { get; set; }

        [JsonProperty("EO_EANLocationDP")]
        public string EOEANLocationDP { get; set; }

        [JsonProperty("EO_EdiCode")]
        public string EOEdiCode { get; set; }

        [JsonProperty("EO_MainChainId")]
        public string EOMainChainId { get; set; }

        [JsonProperty("EO_NetCommerce")]
        public string EONetCommerce { get; set; }

        [JsonProperty("EO_WebPct")]
        public string EOWebPct { get; set; }

        [JsonProperty("EO_ChainCustomer")]
        public string EOChainCustomer { get; set; }

        [JsonProperty("EO_AssortmentOnlyCust")]
        public string EOAssortmentOnlyCust { get; set; }

        [JsonProperty("EO_InvoiceSumGrouping")]
        public string EOInvoiceSumGrouping { get; set; }

        [JsonProperty("EO_ModifiedDateAssortment")]
        public string EOModifiedDateAssortment { get; set; }

        [JsonProperty("EO_CustomsTransitApproved")]
        public string EOCustomsTransitApproved { get; set; }

        [JsonProperty("EO_CRMExternalId")]
        public string EOCRMExternalId { get; set; }

        [JsonProperty("EO_ChainGroupId")]
        public string EOChainGroupId { get; set; }

        [JsonProperty("ModifiedDateTime")]
        public string ModifiedDateTime { get; set; }

        [JsonProperty("CreatedDateTime")]
        public string CreatedDateTime { get; set; }

        [JsonProperty("DataAreaId")]
        public string DataAreaId { get; set; }

        [JsonProperty("Assortment")]
        public Assortment[] Assortment { get; set; }

        [JsonProperty("DlvMonday")]
        public string DlvMonday { get; set; }

        [JsonProperty("DlvTuesday")]
        public string DlvTuesday { get; set; }

        [JsonProperty("DlvWednesday")]
        public string DlvWednesday { get; set; }

        [JsonProperty("DlvThursday")]
        public string DlvThursday { get; set; }

        [JsonProperty("DlvFriday")]
        public string DlvFriday { get; set; }

        [JsonProperty("DlvSaturday")]
        public string DlvSaturday { get; set; }

        [JsonProperty("DlvSunday")]
        public string DlvSunday { get; set; }

        [JsonProperty("LicenceCodes")]
        public LicenceCode[] LicenceCodes { get; set; }
    }

    public class CustomerCollection
    {

        [JsonProperty("customers")]
        public Customer[] Customers { get; set; }
    }

}
