// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace SGSandbox.Models
{

    public class MainChain
    {

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("MainChainId")]
        public string MainChainId { get; set; }

        [JsonProperty("Assortment")]
        public string Assortment { get; set; }

        [JsonProperty("DataAreaId")]
        public string DataAreaId { get; set; }

        [JsonProperty("RecVersion")]
        public string RecVersion { get; set; }

        [JsonProperty("RecId")]
        public string RecId { get; set; }
    }

    public class MainChainCollection
    {

        [JsonProperty("MainChains")]
        public MainChain[] MainChains { get; set; }
    }

}
